### ISSUE TITLE
Version 2.10 broken build and result project rebuild

### ISSUE THREAD

**Issue by mayenjoy** [qtproject/qt-labs-vstools#10]
**Describe the bug**
Version 2.9 is working fine but Version 2.10.2 will make solution rebuild evertime when i touch a cpp file.

**To Reproduce**
1. Go to source file and modify a cpp file.'...'
2. Click on green local debugger button 
3. wait to see PCH file which is compiled 

**Expected behavior**
Only touched cpp file is compiled.

**Desktop (please complete the following information):**
 - Qt VS Tool Version [2.10.2]
 - Visual Studio version [VS2017]

**Comment by kaheimri** [comment]
Many thanks for reporting the issue @mayenjoy . The progress of the reported bug is tracked here: https://bugreports.qt.io/browse/QTVSADDINBUG-1090
Please head over to our own issue tracker if you want to comment or add some more information on the issue.
