### ISSUE TITLE
qt vs tool causes Microsoft Visual Studio Enterprise 2022 (64-bit) to stall

### ISSUE THREAD

**Issue by HanChinese-LIURUI** [qtproject/qt-labs-vstools#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Sometimes when you open the solution, the interface will freeze for a long time and say it’s busy. Sometimes it will freeze for several minutes, and occasionally it will prompt qt vs tool to timeout. Most of the time there will be no prompt, but sometimes the solution will open quickly
After my tests, when the solution is opened and a crash occurs, I disable the network and it will immediately return to normal

**Screenshots**
![image](https://github.com/qt-labs/vstools/assets/53245262/bd96f053-ca3b-4d44-af42-66ecc8e91a5d)

**Desktop (please complete the following information):**
 - Qt VS Tool Version [2.10.1.2]
 - Visual Studio version [ Visual Studio Enterprise 2022 ]

**Additional context**

**Comment by kaheimri** [comment]
Thanks for reporting the issue, we are currently investigation the problem.

**Comment by kaheimri** [comment]
@HanChinese-LIURUI , can you please provide a link to the screenshot you posted? BTW. your issue is now tracked in our public bug-tracking tool here: [QTVSADDINBUG-1115](https://bugreports.qt.io/browse/QTVSADDINBUG-1115)

**Comment by kaheimri** [comment]
@HanChinese-LIURUI, if you find the time to give us a link to the Microsoft page that would be appreciated. You can attach it here: [QTVSADDINBUG-1115](https://bugreports.qt.io/browse/QTVSADDINBUG-1115)
