### ISSUE TITLE
Can not use Creator to build new .ui after open by visual studio

### ISSUE THREAD

**Issue by benben233** [qtproject/qt-labs-vstools#16]
**Describe the bug**
After opening Qt project in visual studio use this extension, using Qt Creator to open the .pro cannot build the new .ui design. Any change will be ignored until use visual studio to build it again.

 - Qt VS Tool 2.10.1
 -  VS2019

**Comment by kaheimri** [comment]
Hello @benben233,
Thank you for reporting the issue. Given that you've already located our official bug tracker and included the matter there, we'd like to solely proceed with tracking the concern on that platform. Link: [QTVSADDINBUG-1119](https://bugreports.qt.io/browse/QTVSADDINBUG-1119)
