### ISSUE TITLE
There is no ‘Create basic .Pro file’

### ISSUE THREAD

**Issue by ZJDATY** [qtproject/qt-labs-vstools#17]
I created a project using VS2019 and wanted to generate a. pro file, but this option is not available in the right-click.

**Screenshots**
![image](https://github.com/qt-labs/vstools/assets/29767049/57fa5855-67cb-4942-a6b6-2c755ecd19af)

**Desktop (please complete the following information):**
 - Qt VS Tool Version 3.0.1
 - Visual Studio version  VS2019
- QT version  5.142

**Comment by Flyingbeanss** [comment]
Hi @ZJDATY ,you can find answer [here](https://stackoverflow.com/questions/77121648/cannt-find-create-pro-file-option-in-qt-vs-tool?).

**Comment by kaheimri** [comment]
Hi, we are sorry to tell you that the .pri/.pro file was explicitly removed from the latest version of the extension as well as support for Qt custom build steps.

If you still need to do the export, there are is only the option to revert to the 2.10.1 version. To do so, disable auto extension updates, uninstall version 3.0.1 and install the 2.10.1 extension from here:  https://download.qt.io/official_releases/vsaddin/2.10.1/
