### ISSUE TITLE
VS Tools Erroneously Includes 'QtWebEngine' Module in Qt Project Settings for Newer QT Versions

### ISSUE THREAD

**Issue by eduardoghi** [qtproject/qt-labs-vstools#18]
**Bug Description**
When I update a legacy Qt project in Visual Studio 2022 with Qt VS Tools, it erroneously adds the 'webengine' module to the Qt project settings. Notably, the C:\Qt\6.5.2\msvc2019_64\include directory lacks the QtWebEngine folder, suggesting a module name change in newer Qt versions.

**To Reproduce**

1. Convert a Qt 6.5.2 project (QT Widgets) for Visual Studio with qmake -tp vc.
2. Open the produced .vcxproj file in Visual Studio 2022.
3. Qt VS Tools alerts with: "You are using a legacy Qt project with Qt Visual Studio Tools. The project format is no longer supported, please update your project to our current version."
4. Update.
5. Confirm the conversion prompt by selecting "Yes".
6. Save the solution file and reload it.
7. Try to run the project.

**Resulting Error**

1>Sistema.vcxproj : error : ERROR running qmake
1>Sistema.vcxproj : error : qmake: (C:/Qt/6.5.2/msvc2019_64/bin/qmake)
1>Sistema.vcxproj : error : qmake: $PWD=C:\Users\myUser\Desktop\Sistema\Sistema\x64\Release\qmake\temp
1>Sistema.vcxproj : error : qmake: Project ERROR: Unknown module(s) in QT: webengine
1>Sistema.vcxproj : error : qmake: Error creating .vcxproj file

**Screenshots**
![image](https://github.com/qt-labs/vstools/assets/124214754/043a06ca-a3f0-4342-99b7-bc04481042f0)

![image](https://github.com/qt-labs/vstools/assets/124214754/38ecdfa1-fc12-402f-bb70-fac9879fc776)

![image](https://github.com/qt-labs/vstools/assets/124214754/f3c5d713-8d9f-4eef-9351-9d8115c71bfb)

![image](https://github.com/qt-labs/vstools/assets/124214754/b7706a66-6fcd-43b9-831c-a50637a5a73a)

**Desktop:**
 - Qt VS Tool Version [3.0.1]
 - Visual Studio version [VS2022 17.7.4 64bits]
 - Windows 11 Pro [22621.2283]

While this issue can be easily fixed by removing the 'webengine' module from the Qt Modules setting, this unexpected behavior can be confusing for users.

**Comment by kaheimri** [comment]
@eduardoghi, thank you for reporting the issue.
It has also been reported in our own issue tracker and further updates will be made here: [QTVSADDINBUG-1126](https://bugreports.qt.io/browse/QTVSADDINBUG-1126)
We have already implemented a fix and are in the process of updating the extension in the VS Marketplace.

**Comment by kaheimri** [comment]
This has been fixed with [9405f4](https://github.com/qt-labs/vstools/commit/9405f497794a81fa207dc214f4f4e8e2faadc895)
