### ISSUE TITLE
(Failed) Modifications to CMakePresets.json and annoying popup ribbon(s) refuse to stay gone.

### ISSUE THREAD

**Issue by dmiller423** [qtproject/qt-labs-vstools#19]
**(Failed) Modifications to CMakePresets.json and annoying popup ribbon**
The new update to vstools latest annoyance wanting to 'convert [CMakePresets.json] to Qt/CMake'
modifies the file in such a way as to render any significant configure presets useless.  
The modified CMakePresets is flawed and not used, even if it was the configurations are forced to hidden.
If you attempt to fix it,  it immediately changes it back to the broken state !!

I was using clang-cl and it has done several things.
1) prefix'd any non hidden configurations "name" with an underscore.
2) removed inheritance from configurations to parents.
3) marked them "hidden": true
4) added it's own configure preset "Qt" (also hidden)
5) added vendor "checksum"

**To Reproduce**
Simply customize a CMakePresets.json with your own configuration(s) and allow it to 'convert' when the annoying popup displays (it will keep coming back, you can't miss it at the top of the editor window).

**Expected behavior**
It's also expected that any modifications will:
- not affect existing configurations in a negative way.
- be transparent, you could have made them inherit "Qt" or just added environment block to inherit.
- be functional,  perhaps the default preset is..  which means nothing as the point of having a configuration is ... 
--- you guessed it:  ability to configure it.  You have removed the ability to do so.

** Annoyances: ***
The tool should not annoy the user to convert at all,  It should be an option in the menu. 
If you choose to do this anyway, it should only be displayed once.. not keep coming back.
If the user clicks the [x] choosing not to convert (or change CMakeSettings.json to CMakePresets.json too !!) it should **_NEVER_** appear again for that project.

**Screenshots**
![image](https://github.com/qt-labs/vstools/assets/1016183/01ad8f27-9ba7-413e-bfd7-40395b6beb66)
![image](https://github.com/qt-labs/vstools/assets/1016183/98be1ac0-2166-4ddc-888e-74d41d2c0dcb)

Put options over annoyances (if you must):
![image](https://github.com/qt-labs/vstools/assets/1016183/07b22c34-972a-44b8-ab0e-3a33cd33c342)

**Desktop**
 - Qt VS Tool Version 3.01
 - Visual Studio version VS2022

**Comment by kaheimri** [comment]
@dmiller423, thank you for reporting the issue. This issue was moved to our official issue tracker and further updates will be made here: [QTVSADDINBUG-1133](https://bugreports.qt.io/browse/QTVSADDINBUG-1133)

**Comment by kaheimri** [comment]
This has been fixed with [51b4bd](https://github.com/qt-labs/vstools/commit/51b4bd) and [dea872](https://github.com/qt-labs/vstools/commit/dea872)

**Comment by dmiller423** [comment]
Excellent,  I assume the package will not be updated for some time..
So I will build and test when I have the time,  thanks.

**Comment by kaheimri** [comment]
We will release a new package next week. Regardless, if your test finds further issues, we may still be able to fix them in time.
