### ISSUE TITLE
Add environment variables during build via WSL

### ISSUE THREAD

**Issue by kotC9** [qtproject/qt-labs-vstools#21]
Feature request

## Problem

I am using Yocto Project to generate an sdk for the build. The sdk is in WSL and to use the sdk, you need to define many variables. When I build a project from Visual Studio, I only specify the path to sysroot and the path to the compiler, some cpp arguments, some ld arguments. This is not enough and the project is not compiled. The build failed at the qmake stage

In the project settings, I didn't find where to set the WSL variables for the build.

## Possible solution

Add a field to the project settings with the input of variables to be used in WSL or add a field with the path to the project settings.sh file with the necessary variables. Before starting the build, use these variables

## Alternative solution

As a temporary solution, I made it so that variables are set when starting WSL. this is a solution on the WSL side

1. Create `/etc/profile.d/qt_variables.sh`
2. Add the necessary variables in file(for example `export TESTVAR=Hello`
3. `wsl --terminate`
4. PROFIT

**Comment by kaheimri** [comment]
Thank you very much for reporting the suggestion; it has been recorded in our public bug tracker, and all further updates will take place there. Here is the link: [QTVSADDINBUG-1144](https://bugreports.qt.io/browse/QTVSADDINBUG-1144)

**Comment by kaheimri** [comment]
Thank you for taking the time to provide your feedback and suggestions. After careful consideration, we have decided not to implement this change at this time. We appreciate your understanding and encourage you to share any other ideas you may have in the future.
