### ISSUE TITLE
Make the greeting (logo with version) in Output optional.

### ISSUE THREAD

**Issue by GShabanov** [qtproject/qt-labs-vstools#22]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when: The non-Qt project is loaded and perhaps even a build occurs, and at this moment Qt decides that it needs to display its logo.

**Describe the solution you'd like**
Make Qt version information optional.

**Comment by acdemiralp** [comment]
Thank you very much for reporting the issue; it has been recorded in our public bug tracker, and all further updates will take place there. Here is the link: [QTVSADDINBUG-1184](https://bugreports.qt.io/browse/QTVSADDINBUG-1184)

**Comment by GShabanov** [comment]
Thank you
