### ISSUE TITLE
Annoying startup "banner" hides build result

### ISSUE THREAD

**Issue by forderud** [qtproject/qt-labs-vstools#28]
`Qt Visual Studio Tools` displays startup timing information in the "Output" window when opening Visual Studio 2022:
![image](https://github.com/qt-labs/vstools/assets/2671400/32b4b0c0-43f7-4f47-bcf2-2c8947a34a25)

This is annoying, since it **hides build results if a build is already triggered**. I'm therefore requesting that display of startup information is made optional, so that it can be disabled.

Associated sources: https://github.com/qt-labs/vstools/blob/v3.2.0/QtVsTools.Package/QtVsToolsPackage.cs#L300

**Comment by acdemiralp** [comment]
Hello, you can disable this behavior via:

Menu -> Extensions -> Qt VS Tools -> Options -> Notifications -> Set "Auto activate console pane" to disabled.

**Comment by forderud** [comment]
Thanks for the suggestion @acdemiralp . Sounds like exactly what I need.

**Comment by kaheimri** [comment]
Thank you for your suggestion! As @acdemiralp mentioned this feature has already been implemented.  If you have any further feedback or suggestions, please feel free to share them. [Add option for activating the console pane on new messages](https://github.com/qt-labs/vstools/commit/2ae465bb114e90af19d4c89746ab04efd95c63a6)
