### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by C33SAR** [qtproject/qt-labs-vstools#3]
I see that `Qt Creator` has the possibility to change the color theme:

![image](https://user-images.githubusercontent.com/103058225/195725156-b8058aad-aa78-42e3-8277-17b9c92105fd.png)

I have Irlen Syndrome (contrast sensitivity) usually white or very black backgrounds cause me severe eye strain/headaches.
I would like to ask for support to themes or a dark theme in the `Visual Studio` `Qt Designer` extension.
It also would help other peoples with a similar problem.

**Comment by pepeu93** [comment]
@C33SAR is best you ask it in the forum, I don't think they read it here.

**Comment by micosta** [comment]
@C33SAR thank you for the suggestion. I've added it to our issue tracking tool: https://bugreports.qt.io/browse/QTVSADDINBUG-1060

**Comment by kaheimri** [comment]
See last comment added by @micosta, please head over to our own issue tracker if you want to comment or add some more information on the issue.
