### ISSUE TITLE
How to integrate VS Tools with Github Actions

### ISSUE THREAD

**Issue by perdrix52** [qtproject/qt-labs-vstools#33]
When building a project on a Github actions runner an error is raised that Qt.Props can't be found.

How should this be addressed?

**Comment by acdemiralp** [comment]
Hello, the process for headless usage such as Github actions is:
- Download the Qt/MsBuild files at https://download.qt.io/official_releases/vsaddin/3.2.0/qt-vsaddin-msbuild-3.2.0-rev.47.zip .
- Extract them somewhere.
- Set the QTMSBUILD environment variable to the location of the QtMsBuild folder prior to building your project.

If this does not solve your problem, please open an issue at: https://bugreports.qt.io/projects/QTVSADDINBUG/

**Comment by kaheimri** [comment]
A related issue was filed here: [Clarify the steps necessary to use the standalone QtMSBuild in CI/CD settings e.g. Azure DevOps](https://bugreports.qt.io/projects/QTVSADDINBUG/issues/QTVSADDINBUG-1228)

**Comment by kaheimri** [comment]
We have added a [Readme](https://github.com/qt-labs/vstools/blob/dev/QtMSBuild/QtMsBuild/readme.md) in commit de8a3ca298627a1bdf1090a8e0bd5f95842c2574 that should address your request.
Thank you for your patience, and please let us know if you need further assistance.
