### ISSUE TITLE
Support solution filters

### ISSUE THREAD

**Issue by rlexmann** [qtproject/qt-labs-vstools#34]
As we updated Qt for our solution (400+ projects) from 5.15 to 6.5, it takes longer to load. I understand that this is probably due to the build system changes between Qt5/6. What frustrates me is that my filter of that solution (100+ projects) takes roughly the same to load and _**I suspect Qt VS Tools are parsing even projects excluded by the filter**_.

Do you have any suggestion how I could speed up solution loading?

**Comment by kaheimri** [comment]
Thank you very much for reporting this suggestion; it has been recorded in our public bug tracker, where all further updates will be shared: [Support solution filters (issue #34)](https://bugreports.qt.io/projects/QTVSADDINBUG/issues/QTVSADDINBUG-1250)

At the moment, I don't have any immediate suggestions to improve load times. Just to confirm, is this related to Visual Studio's [Filtered solutions in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2022)

It would be very helpful if you could add more details about your solution filter setup in the bug report above. If you don't have a Qt account, feel free to provide the details here.

**Comment by kaheimri** [comment]
After thoroughly debugging the solution load process using the complete Qt source tree (converted to .vcxproj first), I was unable to verify your assumption that Qt VS Tools is parsing projects excluded by a filter. We rely entirely on the VSSDK infrastructure, which means only projects included in the filter are forwarded to our extension. Similarly, when a new project is loaded into the filter, only that single project is processed by our extension.

Unfortunately, I cannot provide any further suggestions to speed up the solution loading process at this time.

Thank you for your patience and understanding. If you have any additional questions or need further assistance, please feel free to reach out.
