### ISSUE TITLE
(MsBuild) moc file compilation no longer includes project references

### ISSUE THREAD

**Issue by Ohmslaw79** [qtproject/qt-labs-vstools#35]
**Describe the bug**
During the program compile step (not the MOC compiler) I have recently run into an issue where all of my moc_****.cpp files fail to compile due to unresolvable include paths. I have narrowed this down to the fact that when compiling those files they do not have the paths from referenced projects added to the include paths

**To Reproduce**
1. Create a VS solution with 2 projects 
    - A QT Project that builds a moc file                  (QTProj)
    - Another CPP project that has a file to include (RefProj)
2. In the RefProj properties set VC++ Directories / All Header Files are Public = true
3. Add RefProj as a project reference to the QTProj
4. Include a header file from the RefProj in some header file that compiles to a moc file in the QTProj
5. When you build the solution the raw QTProj files will all compile file, but the Moc file that includes the file from RefProj will fail due to not being able to find the include file

**Expected behavior**
The moc files should have access to all of the includes that the project files do during compilation.

**Desktop (please complete the following information):**
 - Qt VS Tool Version 3.3.0.13
 - VS2022

**Additional context**
We just noticed this issue today (10/22), so if there was an update pushed within the last couple of days it was likely that update that did it. 

Build Log: [QtWidgetsApplication1.log](https://github.com/user-attachments/files/17480093/QtWidgetsApplication1.log)
Minimal Reproducible Example: [Test Solution.zip](https://github.com/user-attachments/files/17480112/Test.Solution.zip)

**Comment by cvwlp** [comment]
Same here, after my Visual Studio updated the Qt Visual Studio Tools to version 3.3.0.13 this morning.

**Comment by rlabbe** [comment]
Same issue, several developers including myself at my company can no longer build with this release.

**Comment by jjsh0503** [comment]
Our company had the same problem. Could not import external library files from moc_***.cpp.
![image](https://github.com/user-attachments/assets/90e170b1-dd95-4385-9e9e-79e57253a3b3)

**Comment by Ohmslaw79** [comment]
This is likely an untenable solution for anyone with numerous project references that are now broken. However, my temporary workaround was to add the required folders to the additional include path in the general build settings for the project. It still seems to be picking up those paths fine, and it has gotten my company building again until this is fixed

**Comment by DamienKochanek** [comment]
We have the same issue. Short term, we reverted to 3.2.0.47, which is still available [here](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/TheQtCompany/vsextensions/QtVisualStudioTools2022/3.2.0.47/vspackage).

**Comment by DavidDeakins** [comment]
We have noticed the same issue in our builds..  Hopefully this will get resolved reasonably quickly.

**Comment by PiotrGizaB3D** [comment]
Same issue here. Gigantic headache... Thank you @DamienKochanek for the link - old version works as expected!

**Comment by kaheimri** [comment]
Thank you very much for reporting this issue; it has been recorded in our public bug tracker, where all further updates will be shared: [(MsBuild) moc file compilation no longer includes project references (issue #35)](https://bugreports.qt.io/projects/QTVSADDINBUG/issues/QTVSADDINBUG-1251)

As a temporary solution, you can roll back to the previous working version by following these steps:

- Uninstall the current version (3.3.0) in Visual Studio.
- Download version 3.2.0 from this link: https://download.qt.io/official_releases/vsaddin/3.2.0/.
- Install version 3.2.0.
- Disable the auto-update functionality in the Visual Studio Extension Manager to prevent future automatic updates.

**Comment by kaheimri** [comment]
We have uploaded a new development release to [qt-vsaddin-msvc2022-x64-3.3.0-rev.46.vsix](https://download.qt.io/development_releases/vsaddin/3.3.0/qt-vsaddin-msvc2022-x64-3.3.0-rev.46.vsix) that should fix your issue.
If you have any additional questions or need further assistance, please feel free to reach out.
