### ISSUE TITLE
After update on actual vstools, earlier successfully compiled project comes errors can't find some include h-files in moc_*.cpp

### ISSUE THREAD

**Issue by Catty82** [qtproject/qt-labs-vstools#37]
**Describe the bug**
Error c1083
Cannot open include file Filname.h
No such file or directory (compiling source moc_*. cpp)

**Desktop (please complete the following information):**
 - Qt VS Tool Version [3.3 rev13]
 - Visual Studio version [e.g. VS2019]

**Comment by Catty82** [comment]
Rollback to qt-vsaddin-msvc2019-x86-3.2.0-rev.47 and getting build success.
Build: 5 succeeded, 0 failed, 0 up-to-date, 0 skipped

**Comment by Catty82** [comment]
vstools 3.3 can't see Additional Include Dirs in project properties C++ - General:
`.;$(ProjectDir)..\..\path1;$(ProjectDir)..\..\path2;%(AdditionalIncludeDirectories)`

When #include "Header.h" changed to 
`..\..\path1\Header.h then see it and compiled.`

**Comment by kaheimri** [comment]
Thank you very much for reporting this issue; it has been recorded in our public bug tracker, where all further updates will be shared: [Cannot find some include h-files in moc_*.cpp (issue #37)](https://bugreports.qt.io/browse/QTVSADDINBUG-1253)

As a temporary solution, you can roll back to the previous working version by following these steps:

- Uninstall the current version (3.3.0) in Visual Studio.
- Download version 3.2.0 from this link: https://download.qt.io/official_releases/vsaddin/3.2.0/.
- Install version 3.2.0.
- Disable the auto-update functionality in the Visual Studio Extension Manager to prevent future automatic updates.

**Comment by Catty82** [comment]
Thanks, we are in wait for fixing soon.
I have been doing such rollback and disable autoupdate.
