### ISSUE TITLE
About VS2022 17.4 Release AMR64 Version vstool

### ISSUE THREAD

**Issue by StefanHope** [qtproject/qt-labs-vstools#5]
Hi everyone, when will the new version be released?
I have tried to build the ARM64 version. But it always show error about
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\TextTemplating\Microsoft.TextTemplating.targets(347,5): error : Compiling transformation: Invalid token 'this' in class, record, struct, or interface member declaration. Line=1, Column=1"
"D:\Testing\vstools-dev\qtmsbuild\QtMsBuild\qt.targets(67,3): error MSB4024: The imported project file "D:\Testing\vstools-dev\qtmsbuild\QtMsBuild\qt_tasks.targets" could not be loaded. Data at the root level is invalid. Line 1, position 1."

Please give me a favor.
Thanksss

**Comment by kaheimri** [comment]
Hi, many thanks for bringing this matter to our attention. So far we did not yet specify a time-frame to release a ARM64 version of our tooling. Since we already got an entry in our official bug tracker [Support QT VS Tools for VS2022 ARM64](https://bugreports.qt.io/browse/QTVSADDINBUG-1055), the progress will be tracked there. In any case, please vote for the feature request on the mentioned page.

**Comment by StefanHope** [comment]
Hi, could you give me a release of this vsix for arm64, event not the formal release? I do really need it, I could not build the source solution. Thanks a lot.

**Comment by kaheimri** [comment]
Hi, I'm not sure I fully understand your request. Do you need a version of Qt VS Tools that run on ARM or do you need a version that runs on x86-64 and supports a build of Qt for ARM?

**Comment by StefanHope** [comment]
I really need a version of Qt VS Tools that run on ARM. Thanks.

**Comment by kasome** [comment]
same issue

**Comment by kaheimri** [comment]
I'm sorry, but currently we cannot provide a build of Qt VS Tools for ARM. To make sure your request is processed in a timely manner, please up-vote the the current Jira task here: https://bugreports.qt.io/browse/QTVSADDINBUG-1055

**Comment by StefanHope** [comment]
already vote it

**Comment by kaheimri** [comment]
We build a version of the tools for ARM. We will probably release an alpha package next week.

**Comment by StefanHope** [comment]
thanks a lot!!!

**Comment by StefanHope** [comment]
> 

Hi, have you already released an alpha package for arm?

**Comment by kaheimri** [comment]
An 'qt-vsaddin-arm_alpha-2.10.0.vsix' ARM alpha package is available here: https://download.qt.io/development_releases/vsaddin/2.10.0/

**Comment by ghost** [comment]
Does it work on Visual Studio for Mac?

**Comment by kaheimri** [comment]
@altitudedashboard unfortunately Visual Studio for Mac does not have support for C++, therefore the Qt VS Tools is not supported there either. Still, you can vote for C++ support on Mac here: https://developercommunity.visualstudio.com/t/support-projects-with-c-c14-c17-language-with-inte/356171 We would glad to support the platform once it becomes  available.

**Comment by StefanHope** [comment]
> An 'qt-vsaddin-arm_alpha-2.10.0.vsix' ARM alpha package is available here: https://download.qt.io/development_releases/vsaddin/2.10.0/

thanks a lot.

**Comment by StefanHope** [comment]
> @altitudedashboard unfortunately Visual Studio for Mac does not have support for C++, therefore the Qt VS Tools is not supported there either. Still, you can vote for C++ support on Mac here: https://developercommunity.visualstudio.com/t/support-projects-with-c-c14-c17-language-with-inte/356171 We would glad to support the platform once it becomes available.

hi, I still cannot install it. Below errors.

1/17/2023 1:45:58 PM - Microsoft VSIX Installer
1/17/2023 1:45:58 PM - -------------------------------------------
1/17/2023 1:45:58 PM - vsixinstaller.exe version:
1/17/2023 1:45:58 PM - 17.4.2120
1/17/2023 1:45:58 PM - -------------------------------------------
1/17/2023 1:45:58 PM - Command line parameters:
1/17/2023 1:45:58 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\stefan\Desktop\qt-vsaddin-arm_alpha-2.10.0.vsix
1/17/2023 1:45:58 PM - -------------------------------------------
1/17/2023 1:45:58 PM - Microsoft VSIX Installer
1/17/2023 1:45:58 PM - -------------------------------------------
1/17/2023 1:46:00 PM - Initializing Install...
1/17/2023 1:46:00 PM - Extension Details...
1/17/2023 1:46:00 PM - 	Identifier         : QtVsTools.8e827d74-6fc4-40a6-a3aa-faf19652b3b8
1/17/2023 1:46:00 PM - 	Name               : Qt Visual Studio Tools
1/17/2023 1:46:00 PM - 	Author             : The Qt Company Ltd.
1/17/2023 1:46:00 PM - 	Version            : 2.10.0.1
1/17/2023 1:46:00 PM - 	Description        : The Qt VS Tools for Visual Studio 2022 allow developers to use the standard development environment without having to worry about any Qt-related build steps or tools.
1/17/2023 1:46:00 PM - 	Locale             : en-US
1/17/2023 1:46:00 PM - 	MoreInfoURL        : https://doc.qt.io/qtvstools/index.html
1/17/2023 1:46:00 PM - 	InstalledByMSI     : False
1/17/2023 1:46:00 PM - 	SupportedFrameworkVersionRange : [4.5,)
1/17/2023 1:46:00 PM - 
1/17/2023 1:46:00 PM - 	SignatureState     : Unsigned
1/17/2023 1:46:00 PM - 	Supported Products : 
1/17/2023 1:46:00 PM - 		Microsoft.VisualStudio.Pro
1/17/2023 1:46:00 PM - 			Version : [17.4,18.0)
1/17/2023 1:46:00 PM - 			ProductArchitecture : amd64
1/17/2023 1:46:00 PM - 		Microsoft.VisualStudio.Premium
1/17/2023 1:46:00 PM - 			Version : [17.4,18.0)
1/17/2023 1:46:00 PM - 			ProductArchitecture : amd64
1/17/2023 1:46:00 PM - 		Microsoft.VisualStudio.Ultimate
1/17/2023 1:46:00 PM - 			Version : [17.4,18.0)
1/17/2023 1:46:00 PM - 			ProductArchitecture : amd64
1/17/2023 1:46:00 PM - 		Microsoft.VisualStudio.Community
1/17/2023 1:46:00 PM - 			Version : [17.4,18.0)
1/17/2023 1:46:00 PM - 			ProductArchitecture : amd64
1/17/2023 1:46:00 PM - 		Microsoft.VisualStudio.Enterprise
1/17/2023 1:46:00 PM - 			Version : [17.4,18.0)
1/17/2023 1:46:00 PM - 			ProductArchitecture : amd64
1/17/2023 1:46:00 PM - 
1/17/2023 1:46:00 PM - 	References         : 
1/17/2023 1:46:00 PM - 		-------------------------------------------------------
1/17/2023 1:46:00 PM - 		Identifier   : Microsoft.VisualStudio.MPF.16.0
1/17/2023 1:46:00 PM - 		Name         : Visual Studio MPF 16.0
1/17/2023 1:46:00 PM - 		Version      : [16.0,17.0)
1/17/2023 1:46:00 PM - 		MoreInfoURL  : 
1/17/2023 1:46:00 PM - 		Nested       : No
1/17/2023 1:46:00 PM - 
1/17/2023 1:46:00 PM - 	Prerequisites      : 
1/17/2023 1:46:00 PM - 		-------------------------------------------------------
1/17/2023 1:46:00 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/17/2023 1:46:00 PM - 		Name         : Visual Studio core editor
1/17/2023 1:46:00 PM - 		Version      : [17.4,18.0)
1/17/2023 1:46:00 PM - 
1/17/2023 1:46:00 PM - 		-------------------------------------------------------
1/17/2023 1:46:00 PM - 		Identifier   : Microsoft.VisualStudio.Component.VC.CoreIde
1/17/2023 1:46:00 PM - 		Name         : Visual Studio C++ core features
1/17/2023 1:46:00 PM - 		Version      : [17.4,18.0)
1/17/2023 1:46:00 PM - 
1/17/2023 1:46:00 PM - 		-------------------------------------------------------
1/17/2023 1:46:00 PM - 		Identifier   : Microsoft.VisualStudio.Component.VC.Tools.ARM64
1/17/2023 1:46:00 PM - 		Name         : MSVC v143 - VS 2022 C++ ARM64 build tools
1/17/2023 1:46:00 PM - 		Version      : [17.4,18.0)
1/17/2023 1:46:00 PM - 
1/17/2023 1:46:00 PM - Signature Details...
1/17/2023 1:46:00 PM - 	Extension is not signed.
1/17/2023 1:46:00 PM - 
1/17/2023 1:46:00 PM - Searching for applicable products...
1/17/2023 1:46:00 PM - Found installed product - Microsoft Visual Studio 2010 Ultimate
1/17/2023 1:46:01 PM - Found installed product - Visual Studio Enterprise 2022 LTSC 17.4
1/17/2023 1:46:01 PM - Found installed product - Global Location
1/17/2023 1:46:01 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by kaheimri** [comment]
@StefanHope, can you please file a bug report over here: https://bugreports.qt.io . As Project please select 'Qt Visual Studio Tools (QTVSADDINBUG)'. As noted by the VSIX installer, it did not find a valid product to install the extension for. You can still try the following steps as outlined here:

1. Rename the *.vsix to *.vsix.zip
2. Change directory into the .zip file
3. Open the .visxmanifest file in your editor
4. Change all version numbers from 17.4 to 17
5. Save and close the file, rename the .zip back to .vsix
6. Give it another try, if it still fails we need to continue on our bug tracker

**Comment by kaheimri** [comment]
The progress of the bug reported is tracked here: https://bugreports.qt.io/browse/QTVSADDINBUG-1055

**Comment by kaheimri** [comment]
The progress of the bug reported is tracked here: https://bugreports.qt.io/browse/QTVSADDINBUG-1055
Please head over to our own issue tracker if you want to comment or add some more information on the issue.
