### ISSUE TITLE
not find qt.natvis.xml error !

### ISSUE THREAD

**Issue by Acreate** [qtproject/qt-labs-vstools#6]
project have resource type file (res.qrc)
in build over. show not find C:\Users\***\AppData\Local\QtMsBuild\qt.natvis.xml error !
my qt version is 6.4.1

**Comment by kaheimri** [comment]
You can disable linking the natvis file into your application by going to: Extensions | Qt VS Tools | Qt | General and set the entry for "Embed .natvis file into PDB" to 'Disable. This should solve your issue.

**Comment by kaheimri** [comment]
The reported issue will be tracked here:

- https://bugreports.qt.io/browse/QTVSADDINBUG-1014
- https://bugreports.qt.io/browse/QTVSADDINBUG-1024

**Comment by kaheimri** [comment]
The progress of the bug reported is tracked here:

- https://bugreports.qt.io/browse/QTVSADDINBUG-1014
- https://bugreports.qt.io/browse/QTVSADDINBUG-1024

Please head over to our own issue tracker if you want to comment or add some more information on the issue.
