### ISSUE TITLE
Can't open existing .pro project

### ISSUE THREAD

**Issue by caxapexac** [qtproject/qt-labs-vstools#8]
**Describe the bug**
Opening .pro files doesn't work (Can't see any error logs)

**To Reproduce**
1. Go to Extensions->QtVsTools->Open qt project file
2. Select .pro file inside my project
3. ...
4. Nothing happens

**Expected behavior**
At least some logs

**Screenshots**
![image](https://user-images.githubusercontent.com/33996246/215260660-c53f58ad-6033-44e1-bb24-f48f85e5fb37.png)

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Qt 6.4.2
 - VS2022

**.pro**
```
QT       += core gui sql printsupport axcontainer

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17
#CONFIG += qwt

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    main.cpp \
    mainwindow.cpp \
    numroom.cpp \
    pdf_cr.cpp \
    pdf_materials.cpp \
    adress.cpp \
    renderer/windowgraphicsview.cpp \
    room.cpp \
    spritecursor.cpp \
    windowsize2d.cpp \
    windowsize3d.cpp \
    changes.cpp \
    finaldimensions.cpp \
    form_window.cpp

HEADERS += \
    adress.h \
    changes.h \
    finaldimensions.h \
    form_window.h \
    mainwindow.h \
    numroom.h \
    pdf_cr.h \
    pdf_materials.h \
    renderer/windowgraphicsview.h \
    room.h \
    spritecursor.h \
    windowsize2d.h \
    windowsize3d.h

FORMS += \
    adress.ui \
    changes.ui \
    finaldimensions.ui \
    form_window.ui \
    mainwindow.ui \
    numroom.ui \
    pdf_cr.ui \
    pdf_materials.ui \
    room.ui \
    windowsize2d.ui \
    windowsize3d.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    img.qrc

```

P.S. Creation of the new qt project works properly

P.P.S. 
![image](https://user-images.githubusercontent.com/33996246/215260861-041fbb46-1ee2-49b1-a060-c145ac81f211.png)
Qt version is set

**Comment by caxapexac** [comment]
![image](https://user-images.githubusercontent.com/33996246/215260820-137dd950-93e7-4685-b533-282a9836d1de.png)
Qt is set btw

**Comment by kaheimri** [comment]
Many thanks for reporting the issue @caxapexac. The progress of the reported bug is tracked here: https://bugreports.qt.io/browse/QTVSADDINBUG-1091
Please head over to our own issue tracker if you want to comment or add some more information on the issue.
