### ISSUE TITLE
Missing QVariant in qt6.natvis.xml 

### ISSUE THREAD

**Issue by dev-nhutl** [qtproject/qt-labs-vstools#9]
I see the qt6.natvis.xml file does not have the visualizer block for QVariant like the qt5.natvis.xml file.
Is there any plan for this? Or does Qt6 actually not need to have the visualizer block for QVariant?

**Comment by kaheimri** [comment]
The issue will be tracked here: https://bugreports.qt.io/browse/QTVSADDINBUG-991

**Comment by kaheimri** [comment]
The progress of the bug reported is tracked here: https://bugreports.qt.io/browse/QTVSADDINBUG-991
Please head over to our own issue tracker if you want to comment or add some more information on the issue.
